blueprint:
  name: RTC – Room Temperature Compensation (15 min fixed)
  description: >
    Regelt automatisch de warmtepomp-offset (+3 t/m -3) op basis van het
    verschil tussen thermostaattemperatuur en ruimtetemperatuur.
    Draait elke 15 minuten: 00, 15, 30, 45.

  domain: automation

  input:
    thermostat:
      name: Thermostaat (basistemperatuur)
      selector:
        entity:
          domain: climate

    room_temp:
      name: Ruimtetemperatuur sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    wp_offset_number:
      name: Warmtepomp offset (number)
      selector:
        entity:
          domain: number

    wp_mode_entity:
      name: WP-modus sensor
      selector:
        entity:
          domain: sensor

    required_mode:
      name: Vereiste WP-modus
      default: "Heat+DHW"
      selector:
        text:

    hysteresis:
      name: Hysterese (°C)
      default: 0.1
      selector:
        number:
          min: 0
          max: 2
          step: 0.1

    warm_threshold_1:
      name: Diff voor -1
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_2:
      name: Diff voor -2
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_3:
      name: Diff voor -3
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_1:
      name: Diff voor +1
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_2:
      name: Diff voor +2
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_3:
      name: Diff voor +3
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

mode: single

########################################
# TRIGGER — werkt ALTIJD in blueprints
########################################
trigger:
  - platform: template
    value_template: "{{ now().minute in [0, 15, 30, 45] }}"

########################################
# Alleen draaien in juiste WP-modus
########################################
condition:
  - condition: template
    value_template: >
      {{ states(wp_mode_entity) | trim | lower ==
         required_mode | trim | lower }}

########################################
# Diff / offset berekenen
########################################
variables:
  set: "{{ state_attr(thermostat, 'temperature') | float }}"
  room: "{{ states(room_temp) | float }}"
  diff: "{{ set - room }}"
  h: "{{ hysteresis | float }}"

  wt1: "{{ warm_threshold_1 | float }}"
  wt2: "{{ warm_threshold_2 | float }}"
  wt3: "{{ warm_threshold_3 | float }}"

  ct1: "{{ cold_threshold_1 | float }}"
  ct2: "{{ cold_threshold_2 | float }}"
  ct3: "{{ cold_threshold_3 | float }}"

  offset: >-
    {% if diff > (ct3 + h) %}
      3
    {% elif diff > (ct2 + h) %}
      2
    {% elif diff > (ct1 + h) %}
      1
    {% elif diff < -(wt3 + h) %}
      -3
    {% elif diff < -(wt2 + h) %}
      -2
    {% elif diff < -(wt1 + h) %}
      -1
    {% else %}
      0
    {% endif %}

########################################
# Offset ACTIE
########################################
action:
  - service: number.set_value
    target:
      entity_id: "{{ wp_offset_number }}"
    data:
      value: "{{ offset }}"
