blueprint:
  name: RTC – Room Temperature Compensation (Complete)
  description: >
    RTC-regeling die op basis van het verschil tussen de thermostaat
    (basistemperatuur) en de ruimtetemperatuur automatisch de
    warmtepomp-offset instelt (+1/+2/+3 of -1/-2/-3).
    Startniveaus zijn instelbaar. Hysterese voorkomt pendelen.
    Automatisering draait alleen wanneer de warmtepomp in de gekozen modus staat.

  domain: automation

  input:
    thermostat:
      name: Thermostaat (basistemperatuur)
      selector:
        entity:
          domain: climate

    room_temp:
      name: Ruimtetemperatuursensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    wp_offset_number:
      name: Warmtepomp water-offset (number entity)
      selector:
        entity:
          domain: number

    wp_mode_entity:
      name: Warmtepomp modus entity
      description: Sensor die aangeeft in welke modus de WP staat (bijv. Heat+DHW)
      selector:
        entity:
          domain: sensor

    required_mode:
      name: Vereiste WP-modus
      description: Automatie werkt alleen bij deze modus (zoals 'Heat+DHW')
      default: "Heat+DHW"
      selector:
        text:

    hysteresis:
      name: Hysterese (°C)
      description: Voorkomt pendelen rondom de drempelwaarden
      default: 0.1
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1

    # Te warm → negatieve correctie
    warm_threshold_1:
      name: Te warm – startpunt voor -1 (°C verschil)
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_2:
      name: Te warm – startpunt voor -2 (°C verschil)
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_3:
      name: Te warm – startpunt voor -3 (°C verschil)
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    # Te koud → positieve correctie
    cold_threshold_1:
      name: Te koud – startpunt voor +1 (°C verschil)
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_2:
      name: Te koud – startpunt voor +2 (°C verschil)
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_3:
      name: Te koud – startpunt voor +3 (°C verschil)
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    interval_minutes:
      name: Update-interval (minuten)
      description: Hoe vaak de RTC-berekening gedaan wordt
      default: 1
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: minutes

mode: single

# Intervaltrigger via template (geen time_pattern meer)
trigger:
  - platform: template
    value_template: >
      {{ (now().minute % (interval_minutes | int(1))) == 0 }}

# Variabelen uit inputs + berekeningen
variables:
  thermostat_entity: !input thermostat
  room_temp_entity: !input room_temp
  wp_offset_entity: !input wp_offset_number
  wp_mode_entity_var: !input wp_mode_entity
  required_mode_var: !input required_mode

  hysteresis_value: !input hysteresis
  warm_t1: !input warm_threshold_1
  warm_t2: !input warm_threshold_2
  warm_t3: !input warm_threshold_3
  cold_t1: !input cold_threshold_1
  cold_t2: !input cold_threshold_2
  cold_t3: !input cold_threshold_3
  interval_minutes: !input interval_minutes

  set: "{{ state_attr(thermostat_entity, 'temperature') | float(0) }}"
  room: "{{ states(room_temp_entity) | float(0) }}"
  diff: "{{ set - room }}"
  h: "{{ hysteresis_value | float(0) }}"

  wt1: "{{ warm_t1 | float(0) }}"
  wt2: "{{ warm_t2 | float(0) }}"
  wt3: "{{ warm_t3 | float(0) }}"
  ct1: "{{ cold_t1 | float(0) }}"
  ct2: "{{ cold_t2 | float(0) }}"
  ct3: "{{ cold_t3 | float(0) }}"

  new_offset: >-
    {% if diff > ct3 + h %}
      3
    {% elif diff > ct2 + h %}
      2
    {% elif diff > ct1 + h %}
      1
    {% elif diff < -wt3 - h %}
      -3
    {% elif diff < -wt2 - h %}
      -2
    {% elif diff < -wt1 - h %}
      -1
    {% else %}
      0
    {% endif %}

# Alleen draaien als WP in de juiste modus staat
condition:
  - condition: template
    value_template: >
      {{ states(wp_mode_entity_var) == required_mode_var }}

# Offset zetten
action:
  - service: number.set_value
    target:
      entity_id: "{{ wp_offset_entity }}"
    data:
      value: "{{ new_offset }}"
