blueprint:
  name: RTC – Room Temperature Compensation (Working v2)
  description: >
    RTC-regeling die op basis van het verschil tussen de thermostaat
    (basistemperatuur) en de ruimtetemperatuur automatisch de
    warmtepomp-offset instelt (+1/+2/+3 of -1/-2/-3).
    Startniveaus zijn instelbaar. Hysterese voorkomt pendelen.
    Interval werkt gegarandeerd elke X minuten (1–30 min).
    Werkt alleen wanneer de warmtepomp in de gekozen modus staat.

  domain: automation

  input:
    thermostat:
      name: Thermostaat (basistemperatuur)
      selector:
        entity:
          domain: climate

    room_temp:
      name: Ruimtetemperatuursensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    wp_offset_number:
      name: Warmtepomp water-offset (number entity)
      selector:
        entity:
          domain: number

    wp_mode_entity:
      name: Warmtepomp modus entity
      selector:
        entity:
          domain: sensor

    required_mode:
      name: Vereiste WP-modus
      default: "Heat+DHW"
      selector:
        text:

    hysteresis:
      name: Hysterese (°C)
      default: 0.1
      selector:
        number:
          min: 0
          max: 1
          step: 0.1

    # Te warm → negatieve correctie
    warm_threshold_1:
      name: Te warm – drempel voor -1 (°C)
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_2:
      name: Te warm – drempel voor -2 (°C)
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_3:
      name: Te warm – drempel voor -3 (°C)
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    # Te koud → positieve correctie
    cold_threshold_1:
      name: Te koud – drempel voor +1 (°C)
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_2:
      name: Te koud – drempel voor +2 (°C)
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_3:
      name: Te koud – drempel voor +3 (°C)
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    interval_minutes:
      name: Update-interval (minuten)
      default: 15
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: minutes

mode: single

# Elke minuut triggeren
trigger:
  - platform: time_pattern
    minutes: "*"

# Alle inputs eerst naar variabelen halen
variables:
  thermostat_entity: !input thermostat
  room_temp_entity: !input room_temp
  wp_offset_entity: !input wp_offset_number
  wp_mode_entity_var: !input wp_mode_entity
  required_mode_var: !input required_mode

  interval: !input interval_minutes

  hysteresis_value: !input hysteresis
  warm_t1: !input warm_threshold_1
  warm_t2: !input warm_threshold_2
  warm_t3: !input warm_threshold_3
  cold_t1: !input cold_threshold_1
  cold_t2: !input cold_threshold_2
  cold_t3: !input cold_threshold_3

  set: "{{ state_attr(thermostat_entity, 'temperature') | float(0) }}"
  room: "{{ states(room_temp_entity) | float(0) }}"
  diff: "{{ set - room }}"
  h: "{{ hysteresis_value | float(0) }}"

  new_offset: >-
    {% if diff > (cold_t3 + h) %}
      3
    {% elif diff > (cold_t2 + h) %}
      2
    {% elif diff > (cold_t1 + h) %}
      1
    {% elif diff < -(warm_t3 + h) %}
      -3
    {% elif diff < -(warm_t2 + h) %}
      -2
    {% elif diff < -(warm_t1 + h) %}
      -1
    {% else %}
      0
    {% endif %}

# Eerst check: zitten we op het juiste interval & in de juiste modus?
condition:
  - condition: template
    value_template: "{{ (now().minute % (interval | int)) == 0 }}"
  - condition: template
    value_template: "{{ states(wp_mode_entity_var) == required_mode_var }}"

# Offset zetten
action:
  - service: number.set_value
    target:
      entity_id: "{{ wp_offset_entity }}"
    data:
      value: "{{ new_offset }}"
