blueprint:
  name: RTC – Room Temperature Compensation (Working)
  description: >
    Werkende RTC-regeling met correcte interval-triggers.
    Draait gegarandeerd elke X minuten (1–30 min).
    Vermijdt alle blueprint-variabele fouten.

  domain: automation

  input:
    thermostat:
      name: Thermostaat
      selector:
        entity:
          domain: climate

    room_temp:
      name: Ruimtetemperatuursensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    wp_offset_number:
      name: Warmtepomp water-offset
      selector:
        entity:
          domain: number

    wp_mode_entity:
      name: Warmtepomp-modus
      selector:
        entity:
          domain: sensor

    required_mode:
      name: Vereiste modus
      default: "Heat+DHW"
      selector:
        text:

    hysteresis:
      name: Hysterese (°C)
      default: 0.1
      selector:
        number:
          min: 0
          max: 1
          step: 0.1

    warm_threshold_1:
      name: Te warm – drempel -1
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_2:
      name: Te warm – drempel -2
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_3:
      name: Te warm – drempel -3
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_1:
      name: Te koud – drempel +1
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_2:
      name: Te koud – drempel +2
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_3:
      name: Te koud – drempel +3
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    interval_minutes:
      name: Interval (minuten)
      default: 15
      selector:
        number:
          min: 1
          max: 30
          step: 1

mode: single

trigger:
  - platform: time_pattern
    minutes: "*"

condition:
  - condition: template
    value_template: >
      {{ now().minute % ( (inputs.interval_minutes | int) ) == 0 }}

  - condition: template
    value_template: >
      {{ states(inputs.wp_mode_entity) == inputs.required_mode }}

action:
  - variables:
      set: "{{ state_attr(inputs.thermostat, 'temperature') | float }}"
      room: "{{ states(inputs.room_temp) | float }}"
      diff: "{{ set - room }}"
      h: "{{ inputs.hysteresis }}"

      ct1: "{{ inputs.cold_threshold_1 }}"
      ct2: "{{ inputs.cold_threshold_2 }}"
      ct3: "{{ inputs.cold_threshold_3 }}"
      wt1: "{{ inputs.warm_threshold_1 }}"
      wt2: "{{ inputs.warm_threshold_2 }}"
      wt3: "{{ inputs.warm_threshold_3 }}"

      offset: >-
        {% if diff > ct3 + h %}
          3
        {% elif diff > ct2 + h %}
          2
        {% elif diff > ct1 + h %}
          1
        {% elif diff < -wt3 - h %}
          -3
        {% elif diff < -wt2 - h %}
          -2
        {% elif diff < -wt1 - h %}
          -1
        {% else %}
          0
        {% endif %}

  - service: number.set_value
    target:
      entity_id: "{{ inputs.wp_offset_number }}"
    data:
      value: "{{ offset }}"
