blueprint:
  name: RTC – Room Temperature Compensation (Fixed 15 min)
  description: >
    Regelt automatisch de warmtepomp-offset (+3 t/m -3) op basis van het
    verschil tussen thermostaattemperatuur en ruimtetemperatuur.
    Draait VAST elke 15 minuten (00, 15, 30, 45). 
    Geen helpers nodig. Werkt alleen in de vereiste WP-modus.

  domain: automation
  input:
    thermostat:
      name: Thermostaat (basistemperatuur)
      selector:
        entity:
          domain: climate

    room_temp:
      name: Ruimtetemperatuursensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    wp_offset_number:
      name: Warmtepomp water-offset (number entity)
      selector:
        entity:
          domain: number

    wp_mode_entity:
      name: Warmtepomp modus sensor
      selector:
        entity:
          domain: sensor

    required_mode:
      name: Vereiste WP-modus
      description: Alleen draaien als WP deze modus heeft.
      default: "Heat+DHW"
      selector:
        text:

    hysteresis:
      name: Hysterese (°C)
      default: 0.1
      selector:
        number:
          min: 0
          max: 2
          step: 0.1

    warm_threshold_1:
      name: Te warm → offset -1 bij diff ≥
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_2:
      name: Te warm → offset -2 bij diff ≥
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_3:
      name: Te warm → offset -3 bij diff ≥
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_1:
      name: Te koud → offset +1 bij diff ≥
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_2:
      name: Te koud → offset +2 bij diff ≥
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_3:
      name: Te koud → offset +3 bij diff ≥
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1


mode: single

##############################################
# TRIGGER – ELKE 15 MINUTEN (00, 15, 30, 45)
##############################################
trigger:
  - platform: time_pattern
    minute: "0"
  - platform: time_pattern
    minute: "15"
  - platform: time_pattern
    minute: "30"
  - platform: time_pattern
    minute: "45"

##############################################
# CONDITION – WP moet in juiste modus staan
##############################################
condition:
  - condition: template
    value_template: >
      {{ states(wp_mode_entity) | trim | lower ==
         required_mode | trim | lower }}

##############################################
# VARIABLES – Logica voor diff & offset
##############################################
variables:
  set: "{{ state_attr(thermostat, 'temperature') | float(0) }}"
  room: "{{ states(room_temp) | float(0) }}"
  diff: "{{ set - room }}"
  h: "{{ hysteresis | float }}"

  wt1: "{{ warm_threshold_1 | float }}"
  wt2: "{{ warm_threshold_2 | float }}"
  wt3: "{{ warm_threshold_3 | float }}"

  ct1: "{{ cold_threshold_1 | float }}"
  ct2: "{{ cold_threshold_2 | float }}"
  ct3: "{{ cold_threshold_3 | float }}"

  offset: >-
    {% if diff > (ct3 + h) %}
      3
    {% elif diff > (ct2 + h) %}
      2
    {% elif diff > (ct1 + h) %}
      1
    {% elif diff < -(wt3 + h) %}
      -3
    {% elif diff < -(wt2 + h) %}
      -2
    {% elif diff < -(wt1 + h) %}
      -1
    {% else %}
      0
    {% endif %}

##############################################
# ACTION – Offset zetten
##############################################
action:
  - service: number.set_value
    target:
      entity_id: "{{ wp_offset_number }}"
    data:
      value: "{{ offset }}"
