blueprint:
  name: RTC – Room Temperature Compensation (Simple thresholds)
  description: >
    RTC-regeling waarbij je alleen de startverschillen instelt waarop de
    warmtepomp-correcties +1/+2/+3 of -1/-2/-3 actief worden. Werkt alleen
    wanneer de warmtepomp in de gekozen verwarmingsmodus staat.

  domain: automation

  input:
    thermostat:
      name: Thermostaat
      selector:
        entity:
          domain: climate

    room_temp:
      name: Ruimtetemperatuursensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    wp_offset_number:
      name: Warmtepomp water-offset
      selector:
        entity:
          domain: number

    wp_mode_entity:
      name: Warmtepomp mode entity
      selector:
        entity:
          domain: sensor

    required_mode:
      name: Vereiste WP modus
      default: "heat+dhw"
      selector:
        text:

    hysteresis:
      name: Hysterese (°C)
      default: 0.1
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1

    warm_threshold_1:
      name: Te warm – startpunt voor -1
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_2:
      name: Te warm – startpunt voor -2
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    warm_threshold_3:
      name: Te warm – startpunt voor -3
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_1:
      name: Te koud – startpunt voor +1
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_2:
      name: Te koud – startpunt voor +2
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    cold_threshold_3:
      name: Te koud – startpunt voor +3
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1

    interval:
      name: Update-interval (seconden)
      default: 60
      selector:
        number:
          min: 10
          max: 600
          step: 10

mode: single

trigger:
  - platform: time_pattern
    seconds: "/{{ interval }}"

condition:
  - condition: template
    value_template: "{{ states(wp_mode_entity) == required_mode }}"

variables:
  set: "{{ state_attr(thermostat, 'temperature') | float }}"
  room: "{{ states(room_temp) | float }}"
  diff: "{{ set - room }}"
  h: "{{ hysteresis }}"

  wt1: "{{ warm_threshold_1 }}"
  wt2: "{{ warm_threshold_2 }}"
  wt3: "{{ warm_threshold_3 }}"

  ct1: "{{ cold_threshold_1 }}"
  ct2: "{{ cold_threshold_2 }}"
  ct3: "{{ cold_threshold_3 }}"

  new_offset: >-
    {% if diff > ct3 + h %}
      3
    {% elif diff > ct2 + h %}
      2
    {% elif diff > ct1 + h %}
      1
    {% elif diff < -wt3 - h %}
      -3
    {% elif diff < -wt2 - h %}
      -2
    {% elif diff < -wt1 - h %}
      -1
    {% else %}
      0
    {% endif %}

action:
  - service: number.set_value
    target:
      entity_id: !input wp_offset_number
    data:
      value: "{{ new_offset }}"
